## Lesson 2.1: Guided Practice

Now that we've gone over the tools for dimensionality reduction, let's put these tools to practice!
First, let's setup our imports. 

In [2]:
import pandas as pd
import numpy as np
import os
from matplotlib import pyplot as plt
import numpy as np
import math
from sklearn.preprocessing import StandardScaler

And read in our data:

In [3]:
iris = pd.read_csv("../../assets/datasets/iris.csv")

Take a Look at the data's head. How is it structured? 

In [4]:
iris.head()

SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

Next, let's break our dataset into x and y values. Remember, our "y" is going to be the class names, which in this case are the varietal names, and "x" is going to be all of the attributes. 

In [5]:
X = iris.loc[:,:"PetalWidth"]
y = iris.loc[:,"Name"]

Since we don't know what units our data was measured in, let's standardize "x"

In [6]:
X_standard = StandardScaler().fit_transform(X)

Next, We'll define the covariance matrix and reduce the dimensions to calculate the eigenvectors and eigenvalues using numpy

In [10]:
cov_mat = np.cov(X_standard.T)

Once we have these, let's check the eigenvectors and eigenvalues to see what we've returned

In [11]:
eigenValues, eigenVectors = np.linalg.eig(cov_mat)

In [13]:
eigenValues, eigenVectors

(array([ 2.93035378,  0.92740362,  0.14834223,  0.02074601]),
 array([[ 0.52237162, -0.37231836, -0.72101681,  0.26199559],
        [-0.26335492, -0.92555649,  0.24203288, -0.12413481],
        [ 0.58125401, -0.02109478,  0.14089226, -0.80115427],
        [ 0.56561105, -0.06541577,  0.6338014 ,  0.52354627]]))

Leading into principal componant analysis, let's select the highest eigenvalues which will be our principal componants

In [16]:
eigenValues[:2]

array([ 2.93035378,  0.92740362])

and sort the values high to low: 

We've found our Eigenvalues (Principal Componants)!