In [2]:
import numpy as np


In [16]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])
print a 
print b
print np.add(a,b)
print np.subtract(a,b)
print np.dot(a,b)
np.dot(-a,-b)

[1 2 3 4 5]
[5 4 3 2 1]
[6 6 6 6 6]
[-4 -2  0  2  4]
35


35